<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BerryApp.Application\BerryApp.Biz.csproj" />
    <ProjectReference Include="..\BerryApp.Domain\BerryApp.Domain.csproj" />
    <ProjectReference Include="..\BerryApp.Infra\BerryApp.Infra.csproj" />
    <ProjectReference Include="..\BerryApp.Shared\BerryApp.Shared.csproj" />
  </ItemGroup>

</Project>
